name: Build

on:
  push:
    branches-ignore:
    - dev
    - main
    - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      working-directory: ./webapp
      run: npm install

    - name: Setup environment variables
      working-directory: ./webapp
      run: |
        echo "ENVIRONMENT = production" >> .env
        echo "PRODUCTION = true" >> .env

    - name: Build
      working-directory: ./webapp
      run: npm run build -- --configuration=production
